# Generated by Django 5.0.3 on 2024-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('phone', models.IntegerField(max_length=12, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Описание проблемы')),
            ],
        ),
    ]
