# Generated by Django 5.0.6 on 2024-06-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='main/info.jpg', null=True, upload_to='main', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
    ]
