# Generated by Django 5.0.3 on 2024-04-18 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_problem_options_alter_order_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(max_length=100, verbose_name='Проблема, неполадка ПК'),
        ),
    ]
