# Generated by Django 5.0.6 on 2024-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_problem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(default='Компьютер не включается', max_length=30, verbose_name='Проблема, неполадка ПК'),
        ),
    ]
