# Generated by Django 5.0.3 on 2024-04-24 05:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_date_alter_problem_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('source', models.CharField(max_length=50, verbose_name='Источник')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=40, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(max_length=30, verbose_name='Проблема, неполадка ПК'),
        ),
    ]
