# Generated by Django 5.0.6 on 2024-06-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_problem_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(max_length=30, verbose_name='Проблема, неполадка ПК'),
        ),
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'verbose_name': 'Все заказы',
                'verbose_name_plural': 'Все заказы',
            },
        ),
    ]
