# Generated by Django 5.0.3 on 2024-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_alter_order_client_alter_order_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='img_articles', verbose_name='Изображение'),
        ),
    ]
