# Generated by Django 5.0.6 on 2024-06-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_problem_problem_allorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Текущие заявки'},
        ),
        migrations.AlterField(
            model_name='allorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.order'),
        ),
    ]
