# Generated by Django 5.0.6 on 2024-06-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_options_alter_allorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorders',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.order'),
        ),
    ]
