# Generated by Django 5.0.6 on 2024-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_allorders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона клиента')),
                ('problem', models.TextField(verbose_name='Неполадка')),
                ('date', models.DateTimeField(verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Все клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Все заявки'},
        ),
        migrations.DeleteModel(
            name='AllOrders',
        ),
    ]
