# Generated by Django 5.0.6 on 2024-06-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_clients_alter_article_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='problem',
        ),
    ]
