# Generated by Django 5.0.3 on 2024-08-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
    ]
