# Generated by Django 5.0.7 on 2024-09-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_article_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AddField(
            model_name='order',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.problem', verbose_name='Неполадка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
